version: '2'

services:
    datacontainer:
        image: netshops/dev_data_container_shopware:latest
        tty: true
        environment:
            SHOPWARE_RELEASE_URL: "http://releases.s3.shopware.com.s3.amazonaws.com/install_5.4.2_2463755ef7e8f738a6b1089e5d936dc27284a40a.zip"
            EXTRACT_PATH: /var/www/html
            FULL_WIPE_ON_REBOOT: "false"
        volumes:
            - /var/www/html
            - ../src:/var/www/src


    datasync:
        image: netshops/dev_data_sync:latest
        depends_on:
            - datacontainer
        volumes_from:
            - datacontainer


    webserver:
        image: netshops/dev_webserver:7.2
        ports:
            - "80:80"
            - "443:443"
        environment:
            TERM: xterm
            VIRTUAL_HOST: dev.local
            SHOPWARE_ENV: dev
            XDEBUG_CONFIG: remote_host=192.168.2.108
        volumes:
            - ./services/webserver/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
        volumes_from:
            - datacontainer
        links:
            - db
            - mailfetcher


    db:
        image: percona:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
            TERM: xterm
        volumes:
            - /var/lib/mysql # To persist the database
            - ./services/percona/percona-server.conf.d/mysqld.cnf:/etc/mysql/percona-server.conf.d/mysqld.cnf
            - ./services/percona/percona-server.conf.d/mysqld_safe.cnf:/etc/mysql/percona-server.conf.d/mysqld_safe.cnf


    mailfetcher:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        environment:
            MH_HOSTNAME: mail.dev.local
            TERM: xterm

    sftp:
        image: netshops/dev_data_sftp
        ports:
            - "2200:2200"
        depends_on:
            - datacontainer
        volumes_from:
            - datacontainer
