version: '2'

services:
    datacontainer:
        image: netshops/dev_data_container_shopware:latest
        tty: true
        environment:
            SHOPWARE_RELEASE_URL: "http://releases.shopware.com/install_5.5.7_f785facc70e39f2ca4292e78739457417f19fbcf.zip"
            EXTRACT_PATH: /var/www/html
            FULL_WIPE_ON_REBOOT: "false"
        volumes:
            - /var/www/html
            - ../src:/var/www/src


    datasync:
        image: netshops/dev_data_sync:latest
        depends_on:
            - datacontainer
        volumes_from:
            - datacontainer


    webserver:
        image: netshops/dev_webserver:7.2
        ports:
            - "127.0.0.1:80:80"
            - "127.0.0.1:443:443"
        environment:
            TERM: xterm
            VIRTUAL_HOST: dev.local
            SHOPWARE_ENV: dev
            XDEBUG_CONFIG: remote_host=192.168.2.108
        volumes:
            - ./services/apache/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
        volumes_from:
            - datacontainer
        links:
            - db
            - mailfetcher


    db:
        image: percona:5.7
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
            TERM: xterm
        volumes:
            - /var/lib/mysql # To persist the database
            - ./services/percona/percona-server.conf.d/mysqld.cnf:/etc/my.cnf.d/mysqld.cnf
            - ./services/percona/percona-server.conf.d/mysqld_safe.cnf:/etc/my.cnf.d/mysqld_safe.cnf


    mailfetcher:
        image: mailhog/mailhog:latest
        ports:
            - "127.0.0.1:1025:1025"
            - "127.0.0.1:8025:8025"
        environment:
            MH_HOSTNAME: mail.dev.local
            TERM: xterm

    sftp:
        image: netshops/dev_data_sftp
        ports:
            - "127.0.0.1:2200:2200"
        depends_on:
            - datacontainer
        volumes_from:
            - datacontainer
